<?xml version="1.0" encoding="utf-8"?>	
	<robot name="box_robots" xmlns:xacro="http://ros.org/wiki/xacro">
		<xacro:property name="box_length" value="0.4" />
                <xacro:property name="box_y" value="0.4" />
                <xacro:property name="box_z" value="0.4" />
		<xacro:property name="link1_radius" value="0.1" />
                <xacro:property name="link1_length" value="0.1" />
                <xacro:property name="link2_radius" value="0.05" />
		<xacro:property name="link2_length" value="0.05" />
                <xacro:property name="link3_radius" value="0.05" />
                <xacro:property name="link3_length" value="0.6" />
 		<xacro:property name="link4_radius" value="0.05" />
		<xacro:property name="link4_length" value="0.05" />
		<xacro:property name="link5_radius" value="0.05" />
		<xacro:property name="link5_length" value="0.45" />
		<xacro:property name="link6_radius" value="0.025" />
		<xacro:property name="link6_length" value="0.04" />
		<xacro:property name="link7_radius" value="0.02" />
		<xacro:property name="link7_length" value="0.02" />
		<xacro:property name="link8_x" value="0.03" />
                <xacro:property name="link8_y" value="0.03" />
                <xacro:property name="link8_z" value="0.04" />
		<xacro:property name="link9_x" value="0.04" />
                <xacro:property name="link9_y" value="0.04" />
                <xacro:property name="link9_z" value="0.02" />
		<xacro:property name="link10_x" value="0.08" />
                <xacro:property name="link10_y" value="0.01" />
                <xacro:property name="link10_z" value="0.02" />
		<xacro:property name="link11_x" value="0.08" />
                <xacro:property name="link11_y" value="0.01" />
                <xacro:property name="link11_z" value="0.02" />


		<material name="blue">
				<color rgba="0 0 1 1"/>
		</material>

		<material name="black">
				<color rgba="0 0 0 1"/>
		</material>

		<material name="white">
				<color rgba="1 1 1 1"/>
		</material>

		<material name="red">
				<color rgba="0.8 0 0 1"/>
		</material>

		<material name="green">
				<color rgba="0 1 0 1"/>
		</material>

		<material name="yellow">
				<color rgba="1 1 0 1"/>
		</material>


		<link name ="world"/>
		<link name="box">
				<visual>
				    <geometry>
				        <box size="${box_length} ${box_y} ${box_z}"/>
				    </geometry>
				    <origin xyz="0 0 ${box_z/2}"/>
				    <material name ="red"/>
				</visual>
				<collision>
					<geometry>
						 <box size="${box_length} ${box_y} ${box_z}"/>
					</geometry>
				</collision>
				<inertial>
					<mass value="50.0"/>
					<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
				</inertial>
		</link>	
		<joint name="world_to_box" type="fixed">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<parent link="world"/>
			<child link="box"/>
		</joint>

		<link name="link1">
				<visual>
				    <geometry>
				        <cylinder radius="${link1_radius}" length="${link1_length}"/>
				    </geometry>
				    <origin xyz="0 0 ${link1_length/2}"/>
				    <material name ="blue"/>
				</visual>
				<inertial>
					<mass value="1.0"/>
					<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
				</inertial>
				<collision>
					<geometry>
						 <cylinder radius="${link1_radius}" length="${link1_length}"/>
					</geometry>
				</collision>
		</link>	
		<joint name="box_link1" type="revolute">
			<axis xyz="0 0 1"/>
			<limit effort="100.0" lower="-3.1416" upper="3.1416" velocity="0.1"/>
			<parent link="box"/>
			<child link="link1"/>
			<origin rpy="0 0 0" xyz="0 0 ${box_z}"/>
		</joint>

		<link name="link2">
				<visual>
				    <geometry>
				        <cylinder radius="${link2_radius}" length="${link2_length}"/>
				    </geometry>
				    <origin rpy='0 1.57 0' xyz="${link2_radius/2} 0 0"/>
				    <material name ="black"/>
				</visual>
				<inertial>
					<mass value="0.5"/>
					<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
				</inertial>
				<collision>
					<geometry>
						 <cylinder radius="${link2_radius}" length="${link2_length}"/>
					</geometry>
				</collision>
		</link>	
		<joint name="link1_link2" type="fixed">
			<parent link="link1"/>
			<child link="link2"/>
			<origin rpy="0 0 0" xyz="${link1_radius} 0 ${link1_length/2}"/>
		</joint>
		<link name="link3">
				<visual>
				    <geometry>
				        <cylinder radius="${link3_radius}" length="${link3_length}"/>
				    </geometry>
				    <origin rpy='0 0 0' xyz="${link3_radius} 0 ${link3_length/2}"/>
				    <material name ="yellow"/>
				</visual>
				<inertial>
					<mass value="5.0"/>
					<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
				</inertial>
				<collision>
					<geometry>
						 <cylinder radius="${link3_radius}" length="${link3_length}"/>
					</geometry>
				</collision>
		</link>	
		<joint name="link2_link3" type="revolute">
			<axis xyz="1 0 0"/>
			<limit effort="100.0" lower="-1.57" upper="1.57" velocity="0.5"/>
			<parent link="link2"/>
			<child link="link3"/>
			<origin rpy="0 0 0" xyz="${link2_length} 0 0"/>
		</joint>
	
		<link name="link4">
				<visual>
				 <geometry>
				     <cylinder radius="${link4_radius}" length="${link4_length}"/>
				 </geometry>
				  <origin rpy='0 1.57 0' xyz="${link4_radius/2} 0 0"/>
				 <material name ="black"/>
				</visual>
				 <inertial>
				 	<mass value="0.5"/>
					<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
				 </inertial>
					<collision>
						<geometry>
							 <cylinder radius="${link4_radius}" length="${link4_length}"/>
						</geometry>
					</collision>
		</link>	
		<joint name="link3_link4" type="fixed">
			<parent link="link3"/>
			<child link="link4"/>
			<origin rpy="0 0 0" xyz="${link3_radius+link4_radius} 0 ${link3_length}"/>
		</joint>

		<link name="link5">
				<visual>
					<geometry>
						<cylinder radius="${link5_radius}" length="${link5_length}"/>
					</geometry>
						<origin rpy='0 0 0' xyz="${link4_radius} 0 ${link5_length/2}"/>
						<material name ="yellow"/>
						</visual>
					<inertial>>
						<mass value="1.0"/>
						<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
					</inertial>
					<collision>
						<geometry>
							 <cylinder radius="${link5_radius}" length="${link5_length}"/>
						</geometry>
					</collision>
		</link>	
		<joint name="link4_link5" type="revolute">
		<axis xyz="1 0 0"/>
		<limit effort="100.0" lower="-1.57" upper="1.57" velocity="0.5"/>
		<parent link="link4"/>
		<child link="link5"/>
		<origin rpy="0 0 0" xyz="${link4_radius} 0 0"/>
		</joint>
		
		<link name="link6">
				<visual>
				 <geometry>
				       <cylinder radius="${link6_radius}" length="${link6_length}"/>
				 </geometry>
					<origin rpy='0 0 0' xyz="0 0 ${link6_length/2}"/>
					<material name ="white"/>
			        </visual>
				 <inertial>
				  <mass value="1.0"/>
				  <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
				 </inertial>
				 	<collision>
						<geometry>
							<cylinder radius="${link6_radius}" length="${link6_length}"/>
						</geometry>
					</collision>
		</link>	
		<joint name="link5_link6" type="revolute">
		<axis xyz="0 0 1"/>
		<limit effort="100.0" lower="-3.1416" upper="3.1416" velocity="0.5"/>
		<parent link="link5"/>
		<child link="link6"/>
		<origin rpy="0 0 0" xyz="${link5_radius} 0 ${link5_length}"/>
		</joint>
		
		<link name="link7">
				<visual>
					<geometry>
						<cylinder radius="${link7_radius}" length="${link7_length}"/>
					</geometry>
						<origin rpy='0 1.57 0' xyz="${link7_radius/2} 0 0"/>
						<material name ="black"/>
				</visual>
					<inertial>
						<mass value="1.0"/>
						<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
				</inertial>
					<collision>
						<geometry>
							<cylinder radius="${link7_radius}" length="${link7_length}"/>
						</geometry>
					</collision>
		</link>	
		<joint name="link6_link7" type="fixed">
		<parent link="link6"/>
		<child link="link7"/>
		<origin rpy="0 0 0" xyz="${link6_radius} 0 ${link6_length/2}"/>
		</joint>

		<link name="link8">
				<visual>
					<geometry>
						<box size="${link8_x} ${link8_y} ${link8_z}"/>
					</geometry>
						<origin rpy='0 0 0' xyz="0 0 ${link8_z/2}"/>
						<material name ="white"/>
				</visual>
					<inertial>
						<mass value="1.0"/>
						<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
					</inertial>
						<collision>
							<geometry>
								<box size="${link8_x} ${link8_y} ${link8_z}"/>
							</geometry>
						</collision>
		</link>	
		<joint name="link7_link8" type="revolute">
		<axis xyz="1 0 0"/>
		<limit effort="100.0" lower="-1.57" upper="1.57" velocity="0.5"/>
		<parent link="link7"/>
		<child link="link8"/>
		<origin rpy="0 0 0" xyz="${link7_radius/2} 0 ${link7_length}"/>
		</joint>
		
		<link name="link9">
				<visual>
					<geometry>
						<box size="${link9_x} ${link9_y} ${link9_z}"/>
					</geometry>
						<origin rpy='0 0 0' xyz="0 0 ${link9_z/2}"/>
						<material name ="white"/>
				</visual>
					<inertial>
						<mass value="0.5"/>
						<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
					</inertial>
						<collision>
							<geometry>
								<box size="${link9_x} ${link9_y} ${link9_z}"/>
							</geometry>
						</collision>
		</link>	
		<joint name="link8_link9" type="fixed">
		<parent link="link8"/>
		<child link="link9"/>
		<origin rpy="0 0 0" xyz="0 0 ${link8_z/2}"/>
		</joint>
		
		<link name="link10">
				<visual>
					<geometry>
						<box size="${link10_x} ${link10_y} ${link10_z}"/>
					</geometry>
						<origin rpy='0 1.57 0' xyz="0 0 ${link9_z+link10_z}"/>
						<material name ="blue"/>
				</visual>
					<inertial>
						<mass value="0.2"/>
						<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
					</inertial>
						<collision>
							<geometry>
								 <box size="${link10_x} ${link10_y} ${link10_z}"/>
							</geometry>
						</collision>
		</link>	
		<joint name="link9_link10" type="revolute">
		<axis xyz="1 0 0"/>
		<limit effort="100.0" lower="0.25" upper="1.18" velocity="0.5"/>
		<parent link="link9"/>
		<child link="link10"/>
		<origin rpy="-1 0 0" xyz="0 ${link9_y/2} ${link9_z/2}"/>
		</joint>
		
		<link name="link11">
				<visual>
					<geometry>
						<box size="${link11_x} ${link11_y} ${link11_z}"/>
					</geometry>
						<origin rpy='0 1.57 0' xyz="0 0 ${link9_z+link10_z}"/>
						<material name ="blue"/>
				</visual>
					<inertial>
						<mass value="0.2"/>
						<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
					</inertial>
						<collision>
							<geometry>
								<box size="${link11_x} ${link11_y} ${link11_z}"/>
							</geometry>
						</collision>
		</link>	
		<joint name="link9_link11" type="revolute">
		<axis xyz="1 0 0"/>
		<limit effort="100.0" lower="-1.18" upper="-0.25" velocity="0.5"/>
		<parent link="link9"/>
		<child link="link11"/>
		<origin rpy="1 0 0" xyz="0 ${-link9_y/2} ${link9_z/2}"/>
		</joint>


	</robot>
